name: build-sys

on:
  workflow_dispatch:

env:
  TIMEOUT: 60
    
jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}
        run: |
          ./fetch-kernel
          ./build-sys ${{ env.TIMEOUT }}
      - name: Upload system image
        uses: actions/upload-artifact@v2
        with:
          name: dockemu-arm64
          path: |
            boot/linux
            boot/initrd.gz
            boot/sys.img
            boot/MD5SUMS
