name: build-sys

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  QEMU_ARCH: aarch64
  QEMU_CPU: cortex-a53
  DEB_ARCH: arm64
  TIMEOUT: 60
  SYS_SIZE: 1

jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}
        run: |
          ./fetch-kernel ${{ env.DEB_ARCH }}
          ./build-sys ${{ env.QEMU_ARCH }} ${{ env.QEMU_CPU }} ${{ env.TIMEOUT }} ${{ env.SYS_SIZE }}
      # - name: Upload system image
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dockemu-arm64
      #     path: |
      #       boot/linux
      #       boot/initrd.gz
      #       boot/sys.img
      # - name: Upload MD5SUMS
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dockemu-arm64.md5
      #     path: boot/MD5SUMS
