name: build-sys

on:
  workflow_dispatch:

jobs:
  build-sys:
    runs-on: ubuntu-latest
    env:
      TIMEOUT: 5
    timeout-minutes: ${{ env.TIMEOUT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        run: |
          ./fetch-kernel
          ./build-sys ${{ env.TIMEOUT }}
