name: build-sys

on:
  workflow_dispatch:
    
jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          time dd if=/dev/zero of=ddtest bs=1M count=1000
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        run: |
          ./fetch-kernel
          ./build-sys
