name: build-sys

on:
  workflow_dispatch:

env:
  TIMEOUT: 60
    
jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        timeout-minutes: ${{ env.TIMEOUT }}
        run: |
          ./fetch-kernel
          ./build-sys ${{ env.TIMEOUT }}
