name: build-sys

on:
  workflow_dispatch:
    inputs:
      qemu_arch:
        description: 'QEMU system target platform'
        required: true
        default: ${{ vars.QEMU_ARCH }}
      qemu_cpu:
        description: 'QEMU system target CPU'
        required: true
        default: ${{ vars.QEMU_CPU }}
      deb_arch:
        description: 'DEBIAN system platform'
        required: true
        default: ${{ vars.DEB_ARCH }}
      timeout:
        description: 'Build time in minutes before machine is powered off'
        default: ${{ vars.TIMEOUT }}
      sys_size:
        description: 'Total system disks size in GBi'
        default: ${{ vars.SYS_SUZE }}
  push:
    branches:
      - master

env:
  QEMU_ARCH: ${{ github.event.inputs.qemu_arch || ${{ vars.QEMU_ARCH }} }}
  QEMU_CPU: ${{ github.event.inputs.qemu_cpu || ${{ vars.QEMU_CPU }} }}
  DEB_ARCH: ${{ github.event.inputs.deb_arch || ${{ vars.DEB_ARCH }} }}
  TIMEOUT: ${{ github.event.inputs.timeout || ${{ vars.TIMEOUT }} }}
  SYS_SIZE: ${{ github.event.inputs.sys_size || ${{ vars.SYS_SIZE }} }}

jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-${{ env.QEMU_ARCH }}
      - name: Build system image
        timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}
        run: |
          ./fetch-kernel ${{ env.DEB_ARCH }}
          ./build-sys ${{ env.QEMU_ARCH }} ${{ env.QEMU_CPU }} ${{ env.TIMEOUT }} ${{ env.SYS_SIZE }}
      - name: Upload system image
        uses: actions/upload-artifact@v3
        with:
          name: dockemu-${{ env.DEB_ARCH }}
          path: |
            boot/linux
            boot/initrd.gz
            boot/sys_*.img
      - name: Upload MD5SUMS
        uses: actions/upload-artifact@v3
        with:
          name: dockemu-${{ env.DEB_ARCH }}.md5
          path: boot/MD5SUMS
