name: build-sys

on:
  workflow_dispatch:
    inputs:
      qemu_arch:
        description: 'QEMU system target platform'
        required: true
        default: 'aarch64'
      qemu_mach:
        description: 'QEMU system target machine'
        required: true
        default: 'virt,virtualization=true,kernel_irqchip=on,gic-version=3'
      qemu_cpu:
        description: 'QEMU system target CPU'
        required: true
        default: 'cortex-a53'
      deb_arch:
        description: 'DEBIAN system platform'
        required: true
        default: 'arm64'
      timeout:
        description: 'Build time in minutes before machine is powered off'
        default: '60'
      sys_size:
        description: 'Total system disks size in GBi'
        default: '1.5'
  # push:
  #   branches:
  #     - master

env:
  QEMU_ARCH: ${{ github.event.inputs.qemu_arch || vars.QEMU_ARCH }}
  QEMU_MACH: ${{ github.event.inputs.qemu_mach || vars.QEMU_MACH }}
  QEMU_CPU: ${{ github.event.inputs.qemu_cpu || vars.QEMU_CPU }}
  DEB_ARCH: ${{ github.event.inputs.deb_arch || vars.DEB_ARCH }}
  TIMEOUT: ${{ github.event.inputs.timeout || vars.TIMEOUT }}
  SYS_SIZE: ${{ github.event.inputs.sys_size || vars.SYS_SIZE }}
  BOOTPATH: boot

jobs:
  build-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-$(echo ${{ env.QEMU_ARCH }}|sed 's/_/-/')
      - name: Build system image
        timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}
        run: |
          ./fetch-kernel ${{ env.DEB_ARCH }}
          ./build-sys ${{ env.QEMU_ARCH }} ${{ env.QEMU_MACH }} ${{ env.QEMU_CPU }} ${{ env.TIMEOUT }} ${{ env.SYS_SIZE }}
      - name: Build Vagrant Box
        run: |
          ./build-box
      - name: Upload system image
        uses: actions/upload-artifact@v3
        with:
          name: dockemu-${{ env.DEB_ARCH }}
          path: |
            ${{ env.BOOTPATH }}/*
      - name: Upload MD5SUMS
        uses: actions/upload-artifact@v3
        with:
          name: dockemu-${{ env.DEB_ARCH }}.md5
          path: boot/MD5SUMS
