name: build-sys

on:
  workflow_dispatch:

jobs:
  build-sys:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-aarch64
      - name: Build system image
        run: |
          ./fetch-kernel
          ./build-sys ${{ jobs.build-sys.timeout-minutes }}
